# Generated by Django 4.2 on 2023-04-23 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_rename_date_buyer_purchase_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentimentAnalysis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentiment_score",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("sentiment_label", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TweepyTweet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tweet_id", models.CharField(max_length=255, unique=True)),
                ("user_id", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("tweet_text", models.TextField()),
                ("created_at", models.DateTimeField()),
                (
                    "sentiment",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.sentimentanalysis",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="buyer",
        ),
        migrations.DeleteModel(
            name="producat",
        ),
        migrations.DeleteModel(
            name="seller",
        ),
        migrations.AddField(
            model_name="sentimentanalysis",
            name="tweet",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="app.tweepytweet"
            ),
        ),
    ]
