# Generated by Django 4.2 on 2023-04-23 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_sentimentanalysis_tweepytweet_delete_buyer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentimentanalysis",
            name="sentiment_score",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="sentimentanalysis",
            name="tweet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.tweepytweet",
            ),
        ),
    ]
