# Generated by Django 4.2 on 2023-04-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_sentimentanalysis_sentiment_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweepytweet",
            name="tweet_id",
            field=models.CharField(max_length=255),
        ),
    ]
