# Generated by Django 4.2 on 2023-04-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_tweepytweet_tweet_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweepytweet",
            name="score",
            field=models.FloatField(default=0),
        ),
    ]
